### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by robotrono** [rumd3x/spotify-nightbot#2]
Hi! 

Is it possible to add a command to show the song that is playing in Spotify?

Example: 

User: !song
Nightbot: Song: lala - lala

**Comment by rumd3x** [comment]
After a closer look at the Nightbot API, I believe yes it is possible.

Although Nightbot does not support external webhooks for custom commands, or even custom variables for its command messages, so this would by no means be a clean solution.

Yet, it might be possible to achieve this effect by manipulating with some trickery the [Custom Commands Resource](https://api-docs.nightbot.tv/#custom-command-resource), the idea here is to:
1. Add a new custom command and store the created ID.
2. Constantly edit the command's message with the current song.

Things that still uncertain and might not make it viable:
- API rate limit for these endpoints?
- Errors if the user already has the command created?
- Errors if the user deletes the custom created command via the nightbot panel?
- Needs a new configuration on my side for a custom "No song playing currently" message.
- Needs a way to enable/disable chat message sending a command updating independently.

**Comment by robotrono** [comment]
I hope this feature can be implemented without problems. Thank you for the service you provide.

**Comment by rumd3x** [comment]
I'm happy to announce that I finally had some spare time and was able to implement this feature. 

It should be live in the next few hours. 

You will need to change your configuration to enable the **!song** in the user interface and also make sure to reconnect your Nightbot account, since a new permission is necessary to manage commands.

**Comment by robotrono** [comment]
Thank you very much for the great work! I will be looking forward to the update.

**Comment by rumd3x** [comment]
Just confirmed the new version is already live and working as intended. Enjoy.

![image](https://user-images.githubusercontent.com/12579932/120949965-20e7b580-c71c-11eb-911c-6eeeba59aa58.png)

**Comment by robotrono** [comment]
Works fine, thanks so much!

![image](https://user-images.githubusercontent.com/5517878/120950363-3b199780-c70c-11eb-8360-0e40ec140ea3.png)

Btw, How many seconds does it take for the command to update?

**Comment by rumd3x** [comment]
Hey @robotrono u're welcome.

The Spotify API is polled every minute for all users and is broadcasted instantly in case newer information is found.
